platform :ios, '10.0'

target 'sdyCloudLive' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

pod 'AFNetworking'
pod 'YYKit'
pod 'Masonry'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'SVProgressHUD'
pod 'MJRefresh'

end
